[project]
name = "quincy"
version = "0.0.1"
authors = [{ name = "Drew Whitney", email = "drewlwhitney@gmail.com" }]
maintainers = [{ name = "Drew Whitney", email = "drewlwhitney@gmail.com" }]
description = "Quincy lets you create sequences to automate lab experiments."
readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.13"
dependencies = [
    "comtypes==1.4.11",
    "jinja2==3.1.6",
    "minimalmodbus==2.1.1",
    "polars==1.31.0",
    "pyqt6==6.9.1",
    "pyqtgraph==0.13.7",
    "pyserial==3.5",
    "tendo==0.3.0",
]

[project.urls]
Repository = "https://github.com/Maughan-Lab/Quincy-New"

[project.scripts]
quincy = "quincy.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
